# Generated by Django 5.0.1 on 2024-11-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eletrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(max_length=255)),
                ('nome', models.TextField(max_length=255)),
                ('local', models.TextField(max_length=255)),
                ('instrutor', models.TextField(max_length=255)),
                ('status', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='eletronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(max_length=255)),
                ('nome', models.TextField(max_length=255)),
                ('local', models.TextField(max_length=255)),
                ('instrutor', models.TextField(max_length=255)),
                ('status', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=255)),
                ('data', models.DateField()),
                ('evento', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mecanica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(max_length=255)),
                ('nome', models.TextField(max_length=255)),
                ('local', models.TextField(max_length=255)),
                ('instrutor', models.TextField(max_length=255)),
                ('status', models.TextField(max_length=255)),
            ],
        ),
    ]
